### ISSUE TITLE
Global Master - Recenzja Kodu

### ISSUE THREAD

**Issue by ghost** [reklamaKOX/globalmaster-task#1]
Dzień dobry,
Przeanalizowałem wykonane przez Pana zadanie. Pewne rzeczy można poprawić:
- zamiast znaczników \<font\>, które nie są obsługiwane w nowszej wersji HTML, możesz ostylować czcionki korzystając z właściwości CSS
- kafelki kategorii na stronie rozkładają się nierównomiernie
- nazewnictwo identyfikatorów znaczników jest niejasne, lepiej jest nadawać im bardziej zrozumiałe nazwy
- brak podpiętej czcionki, której używamy na naszej stronie ('Montserrat'), możesz to zrobić korzystając z Google API

Pozdrawiam
Grzegorz Dziura | IT Specialist
Global Master

**Comment by reklamaKOX** [comment]
Witam, strona została poprawiona

**Comment by ghost** [comment]
Dzień dobry,
rzeczywiście jest już lepiej. Przyjmiemy Pana na praktyki.

Potrzebne dokumenty bardzo proszę wysłać gdy będzie mieć Pan możliwość (pocztą lub elektronicznie na e-mail).
Potrzebujemy również określić w jakim przedziale czasowym miałby Pan zacząć praktyki.
Pozdrawiam.

**Comment by reklamaKOX** [comment]
Witam, przesyłam zaświadczenie o przyjęciu na praktyki.

pon., 16 wrz 2024, 11:03 użytkownik GrzegorzDroid ***@***.***>
napisał:
